### ISSUE TITLE
Not working on Firefox 49

### ISSUE THREAD

**Issue by hamityanik** [antelle/small-color-picker#2]
Hi,

I'm using Firefox version 49.0. Small color picker is not working. When click to color wheel, nothing happens.

**Comment by antelle** [comment]
Hello,
For me, it's working in Firefox.
Is there anything in dev console?

**Comment by hamityanik** [comment]
Hello,

Nothing in dev console. 
I've recorded a video of issue.

![small-color-picker-gif](https://cloud.githubusercontent.com/assets/16164957/19482374/97a7590e-9559-11e6-9130-b8b6494f2ae0.gif)

**Comment by antelle** [comment]
ok for my on latest version, please feel free to submit a patch, if it's still failing for you
