### ISSUE TITLE
Wrong popup positioning

### ISSUE THREAD

**Issue by AleCaste** [antelle/small-color-picker#3]
I have a complex webpage layout and the popup positioning calculations of the plugin (excellent plugin by the way!) are wrong.
I replaced the line in `circle-picker.js` that says...
```var parentPosition = _parent.position(), parentWidth = _parent.outerWidth(), parentHeight = _parent.outerHeight(),```
... with...
```var parentPosition = _parent.offset(), parentWidth = _parent.outerWidth(), parentHeight = _parent.outerHeight(),```
... and now the popup positioning is working fine for me.
Could you have a look at this?
Thanks!
Alex

**Comment by antelle** [comment]
Sure, it must be offset, to be able to work with absolute positioning. Fixing it now...

**Comment by antelle** [comment]
done, v1.3.0
thanks for that 👍

**Comment by AleCaste** [comment]
Excellent!
